# fly.toml app configuration file generated for chatserver1 on 2024-03-25T17:58:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatserver1'
[[services]]
  internal_port = 8081  # Порт вашего WebSocket-сервера
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "8081"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
